name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 15.8.0
      uses: actions/setup-node@v2
      with:
        node-version: "15.8.0"
    - name: Build
      run: |
        npm install --include-dev
        npm run build
        cp -r assets/* dist/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
    - name: Push to S3
      run: |
        aws s3 sync dist/ s3://template.danherlihy.me
